# Common Brewfile for server and workstation setup
# Install with: brew bundle --file=Brewfile

# Formula packages
brew "atuin"
brew "bat"
brew "curl"
brew "delta"
brew "difftastic"
brew "direnv"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "gitleaks"
brew "git"
brew "git-branchless"
brew "gnupg"
brew "gum"
brew "herdr"
brew "htop"
brew "jj"
brew "jq"
brew "lazygit"
brew "lesspipe"
brew "mise"
brew "neovim"
brew "neovim-remote"
brew "ripgrep"
brew "ripgrep-all"
brew "shellcheck"
brew "shellharden"
brew "shfmt"
brew "stow"
brew "tldr"
brew "tmux"
brew "tmuxinator"
brew "tpm"
brew "tree"
brew "uv"
brew "vim"
brew "wget"
brew "yq"
brew "zellij"
brew "zoxide"
