# Jujutsu (jj) Configuration
# See https://jj-vcs.github.io/jj/latest/config/ for full documentation

[user]
# User identity - set in ~/.jjconfig.local.toml for machine-specific values
# name = "Your Name"
# email = "your.email@example.com"

[ui]
editor = "nvim"
pager = "less -FRX"
# Leave ui.diff.tool unset → jj diff uses the built-in text diff

[aliases]
# Git-like aliases
st = ["status"]
sw = ["checkout"]
br = ["branch", "list"]
co = ["checkout"]
ci = ["commit"]

# Show graph of commits
graph = ["log", "--graph"]
# Show recent commits
recent = ["log", "-r", "@", "--limit", "10"]

# External diff aliases
difft = ["diff", "--tool=difft"]
delta = ["diff", "--tool=delta"]
diffbat = ["diff", "--tool=diffbat"]

[revsets]
# Show commits in current branch that aren't in main
feature = "@ - main"

[git]
# Automatically create a bookmark for each local branch
auto-local-bookmark = true

# Make commits look identical to Git commits
set-committer = false

[snapshot]
# Automatically snapshot working copy changes
auto-track = "all"

[template-aliases]
compact_log = '''
separate(" ",
  change_id.short(),
  if(current_working_copy, "@"),
  branches,
  tags,
  bookmarks,
  if(conflict, "conflict"),
  if(divergent, "divergent"),
  if(hidden, "hidden"),
  description.first_line(),
)
'''

[ui.diff-tools]
# Difftastic (two-way tree diff)
difft = ["difft", "--color=always", "$left", "$right"]

# Delta (needs unified diff piped in)
delta = ["sh", "-lc", "diff -ruN \"$left\" \"$right\" | delta --color=always"]

# Bat (show unified diff with syntax highlighting)
diffbat = ["sh", "-lc", "diff -ruN \"$left\" \"$right\" | bat --language=diff"]

# Pull in machine-local overrides
[include]
files = ["~/.jjconfig.local.toml"]
