onboarding = false

[theme.custom]
accent = "#f9e2af"
surface_dim = "#313244"
surface0 = "#45475a"
surface1 = "#585b70"
overlay0 = "#a6adc8"
overlay1 = "#cdd6f4"

[ui]
agent_panel_sort = "spaces"
accent = "#f9e2af"
pane_borders = true
pane_gaps = true
show_agent_labels_on_pane_borders = true

[keys]
prefix = "ctrl+space"
